### ISSUE TITLE
In Visual Studio 2015 Community

### ISSUE THREAD

**Issue by duongphuhiep** [bytefish/TinyCsvParser#1]
Severity	Code	Description	Project	File	Line
Error		Could not install package 'TinyCsvParser 0.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by bytefish** [comment]
Please make sure, your project targets .NET 4.5. Your project seems to target .NET 4.0 and the library isn't compatible with it. I will investigate, if I have missed to specify it in the NuGet specification file and update this issue accordingly.

In the meantime, could you try to set your projects target runtime to 4.5 and let me know, if it helps?

**Comment by bytefish** [comment]
I have reviewed the NuGet package and it targets .NET 4.5. Please upgrade the project and let me know, if it solves the problem. Please reopen the ticket if the problem still occurs with a .NET 4.5 target.
