### ISSUE TITLE
Build on fresh clone Fails

### ISSUE THREAD

**Issue by Jcouls29** [bytefish/TinyCsvParser#16]
With a fresh clone, using VS 2015, the build fails. With different versions of .NET Core, it doesn't seem to work.  The version is not specified in global.json.  This may be part of the issue.

**Comment by bytefish** [comment]
I have deleted the XPROJ files, which may cause the problem. 

I was able to build the projects with Visual Studio 2015 Update 3:

1. Open Visual Studio
2. File -> Open -> Project / Solution ...
3. Open the TinyCsvParser ``project.json`` file:

![image](https://cloud.githubusercontent.com/assets/239373/21079450/2f5be406-bf92-11e6-88f7-f27d4c504e3d.png)

4. Now right click on the Solution, which has been created and choose: Add -> Existing Project ...
5. Navigate to the TinyCsvParser.Test ``project.json`` and add it to the Solution.
6. Build the Solution.

![image](https://cloud.githubusercontent.com/assets/239373/21079467/c711fdee-bf92-11e6-866a-80ffc8b646df.png)
