### ISSUE TITLE
[Question] Progress report

### ISSUE THREAD

**Issue by Floppixx** [bytefish/TinyCsvParser#19]
First of all, thank you for this blazing fast parser. Realy clean code style and fresh c# langues features. 

Is it possible to get a progress report to fill a progressba? Even if your parser is fast but 1GB file can slow that a bit. I guess Plinq does not support it,

**Comment by bytefish** [comment]
The Parser is a Streaming Parser, which means it doesn't read the entire file before parsing it. As such there is no way to know the number of lines in a file, before you have read it to the end. 

I have played around with a ``StreamReader`` to read the data from. Then I tried to calculate the number of bytes read so far and divide it by the file size. But the ``StreamReader`` buffers data and may read ahead, so it doesn't yield correct results.

Maybe you have a better idea! You could easily plug a ``StreamReader``-based implementation into the Framework, like I did here: https://github.com/bytefish/TinyCsvParser/blob/master/TinyCsvParser/TinyCsvParser/CsvParserExtensions.cs#L27.
