### ISSUE TITLE
EnumConverter not registering TypeConverter

### ISSUE THREAD

**Issue by IrishTechnician** [bytefish/TinyCsvParser#20]
Greetings,

Not sure if this is a bug or me not understanding CustomConverters. I am trying to create a string to enum converter. I am using the below to convert a field to an enum:

```
--snip
MapProperty(3, x => x.TransactionType).WithCustomConverter(new TransactionTypeConverter()); 
--line that returns error
--snip 

public class TransactionTypeConverter : EnumConverter<TransactionType>
{
    protected override bool InternalConvert(string value, out TransactionType result)
    {
        result = value == "payt" ? TransactionType.Payment : TransactionType.Charge;
        return true;
    }
}
```

However when running it returns the following: 

> No TypeConverter registered for Type Messages.TransactionType

Looking into your code it appears that the EnumConverter is missing from the TypeConverterProvider constructor. Am I missing something here?

**Comment by IrishTechnician** [comment]
For reference it works when you remove the .WithCustomConverter, for example the following works with nothing else changed:

` MapProperty(3, x => x.TransactionType, new TransactionTypeConverter());`

**Comment by bytefish** [comment]
I will remove the ``WithCustomConverter`` method in the next version. It was originally for overriding existing registrations for a Type, but you might need multiple registrations for a type depending on format and so on. 

Your second version is correct. It's not a bug, but the API is misleading and I will correct it in the next version.
