### ISSUE TITLE
Type converter bug - "No TypeConverter registered" for the type converter I am trying to register?

### ISSUE THREAD

**Issue by mikechamberlain** [bytefish/TinyCsvParser#22]
Thank you for an otherwise excellent library, and my apologies if this is a problem with my code.

I've tried all I can can to create a type converter for `System.Uri` as described in [the docs](http://bytefish.github.io/TinyCsvParser/sections/userguide/typeconverter.html#parsing-custom-formats) - it seems that it should be simple, but so far I haven't been able to get it to work. (Though as far as I can see, there is no actual implementation of `ITypeConverter` anywhere in the docs.)

Below an [MCVE ](https://stackoverflow.com/help/mcve) showing the problem. An exception is thrown in the constructor for `MyMapping`:

> 'TinyCsvParser.Exceptions.CsvTypeConverterNotRegisteredException' occurred in TinyCsvParser.dll but was not handled in user code
> Additional information: No TypeConverter registered for Type System.Uri

Well OK - but that's exactly what I am trying to do! Please enlighten me.

I pushed the whole example to https://github.com/mikechamberlain/TinyCsvParserBug

```csharp
using System;
using System.Linq;
using System.Text.RegularExpressions;
using NUnit.Framework;
using TinyCsvParser;
using TinyCsvParser.Mapping;
using TinyCsvParser.TypeConverter;

namespace TinyCsvBug
{
    [TestFixture]
    class Test
    {
        [Test]
        public void Bug()
        {
            var csvParserOptions = new CsvParserOptions(false, new []{','});
            var csvMapper = new MyMapping();
            var csvParser = new CsvParser<Model>(csvParserOptions, csvMapper);
            var csv = "http://www.google.com";
            
            var result = csvParser
                .ReadFromString(new CsvReaderOptions(new[] { Environment.NewLine }), csv)
                .ToList();

            Assert.AreEqual("http://www.google.com", result[0].Result.Uri.ToString());
        }
    }

    internal class MyMapping : CsvMapping<Model>
    {
        public MyMapping()
        {
            // EXCEPTION HERE
            // TinyCsvParser.Exceptions.CsvTypeConverterNotRegisteredException : No TypeConverter registered for Type System.Uri
            MapProperty(0, x => x.Uri)
                .WithCustomConverter(new HttpUriConverter());
        }
    }
    
    internal class HttpUriConverter : ITypeConverter<Uri>
    {
        private static readonly Regex MatchHttp = new Regex(@"^\s*https?://");

        public bool TryConvert(string value, out Uri result)
        {
            result = null;
            if (!MatchHttp.IsMatch(value))
            {
                return false;
            }
            result = new Uri(value);
            return true;
        }

        public Type TargetType => typeof(Uri);
    }

    class Model
    {
        public Uri Uri { get; set; }
    }
}
```

**Comment by mikechamberlain** [comment]
Oh I've just seen #20. Very frustrating! Just wasted a few hours on an issue with the documentation.

**Comment by bytefish** [comment]
Documentation Issues fixed. I will deprecate the ``WithCustomConverter`` method in the next release.
