### ISSUE TITLE
Dynamic or Untyped Mappings and Output

### ISSUE THREAD

**Issue by seanfisher** [bytefish/TinyCsvParser#23]
Thanks for what looks to be a great library! I'm creating an application that needs to do some CSV processing without knowing either the mappings or the structure of the input data at compile-time. At runtime I have both the input data (of course) and the mapping information (each of the destination columns and whether I should pull them from a column in the source or provide a default or static value).

So I have two questions:

1. Is there a way to construct the mapping object for TinyCsvParser at runtime? I guess I could construct a runtime expression manually using Linq. It would help if there were an overload to the mapping to pass in the column names as strings instead of just expressions (especially since it currently looks like the expressions are just mapped back to strings through reflection eventually).
2. Is there a way to receive some `dynamic` or `IEnumerable<KeyValuePair<string, string>>` (for header -> value) back from TinyCsvParser?

Thanks!

**Comment by bytefish** [comment]
I will need some time to think about it. I am just writing down some ideas below on how to extend the library. But if it is urgent, then probably the ``CsvHelper`` has the features you need?



## Sample Dynamic Mapper ##

I think one can do a mapping based on Column Names with a class like this (I haven't tested it). That requires a Header to be passed into the Constructor to instantiate it. But I am unsure how to plug it into the existing pipeline. 

Any ideas are welcome.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using TinyCsvParser.Model;

namespace TinyCsvParser.Mapping
{
    public class CsvMappingDynamic<TEntity> : CsvMapping<TEntity>
        where TEntity : class, new()
    {
        private readonly IDictionary<string, int> columnNameToIndexMapping;

        private readonly CsvMapping<TEntity> csvMapping;

        public CsvMappingDynamic(TokenizedRow header)
        {
            // The Header is also a TokenizedRow:
            header
                // Get All Tokens (Column Names):
                .Tokens
                // Enumerate the Columns:
                .Select((columnName, position) => new
                {
                    ColumnName = columnName,
                    Position = position
                })
                // And Create a Dictionary for faster Lookup:
                .ToDictionary(x => x.ColumnName, x => x.Position);
        }

        protected CsvPropertyMapping<TEntity, TProperty> MapProperty<TProperty>(string columnName, Expression<Func<TEntity, TProperty>> property)
        {
            // Make Sure the Value is available in the Mapping:
            if(!columnNameToIndexMapping.ContainsKey(columnName))
            {
                throw new InvalidOperationException(string.Format("No matching header column for name '{0}'", columnName));
            }

            // Get the Column Index:
            int position = columnNameToIndexMapping[columnName];

            // And now we can map by index as in the original mapping:
            return MapProperty(position, property);
        }
    }
}
```

## Existing Pipeline ##

The current CSV Pipeline for the Parsing. The only thing I do with the header is to skip it or not. But I don't know how to instantiate the Mapping at this point. An ``Initialize`` method also seems to be 

```csharp
public ParallelQuery<CsvMappingResult<TEntity>> Parse(IEnumerable<Row> csvData)
{
    if (csvData == null)
    {
        throw new ArgumentNullException("csvData");
    }

    var query = csvData
        .Skip(options.SkipHeader ? 1 : 0)
        .AsParallel();

    // If you want to get the same order as in the CSV file, this option needs to be set:
    if (options.KeepOrder)
    {
        query = query.AsOrdered();
    }

    query = query
        .WithDegreeOfParallelism(options.DegreeOfParallelism)
        .Where(row => !string.IsNullOrWhiteSpace(row.Data));

    // Ignore Lines, that start with a comment character:
    if(!string.IsNullOrWhiteSpace(options.CommentCharacter)) 
    {
        query = query.Where(line => !line.Data.StartsWith(options.CommentCharacter));
    }
                
    return query
        .Select(line => new TokenizedRow(line.Index, options.Tokenizer.Tokenize(line.Data)))
        .Select(fields => mapping.Map(fields));
}
```

**Comment by josh75337** [comment]
How do you recreate this warning? I downloaded the 2.1 branch and set it up and ran the unit test and did not get that warning.

**Comment by Angr1st** [comment]
I just found this Issue and was wondering 
- if there could be an even more dynamic approach with creating a class to map to at runtime?
-  Where exactly are you getting that double enumerable error? Inside of the .Parse(rowData) or when trying to do csvDataArray.AsEnumerable().First()?

**Comment by bytefish** [comment]
I am currently reworking the API to allow dynamic mappings. I am not sure about the final API, the above are thought experiments. If you have ideas, please let me know. 😎

**Comment by Angr1st** [comment]
Well based on what I have seen how TinyCSV works I would personally try creating a class to map to at runtime based on the headers of the csv file but I have not really taken a look at how TinyCSV works internally. I would use CodeDOM to archieve this but If you want efficiency you might take a look at reflection.emit and writíng low level IL ([See Stackoverflow](https://stackoverflow.com/questions/2366921/reflection-emit-vs-codedom)).

I want to write a Library combining TinyCSV with Elasticsearch.NET to import big csv files with differing structure into elasticsearch in which I dont care about the structure as long as the headers are set correctly.

**Comment by bytefish** [comment]
Thanks for the suggestions. I won't have much time the weeks ahead, so I won't be able to work on it. I will create a branch soon with dynamic mappings included.

**Comment by Angr1st** [comment]
Hello bytefish FYI I have continued to look into dynamically generating POCO Classes to map to and the only real way I found that may work is using reflection.emit as CodeDOM doesn't work with .net core as it cant compile your generated code. 

I'm really looking forward to see how you archieve the dynamic mappings

**Comment by Angr1st** [comment]
Hello bytefish after a little bit of research I think that the only way for my dll tinycsv to elasticsearch is to leverage system.reflection.emit to create the POCO Types at runtime. So basically building a programm which builds the functionality I want using IL at runtime for each CSV-file that has the same Headernames. I came to this conclusion as elasticsearch.net also needs POCO classes and does not expose any dynamic capabilitys as anonymous class don´t cut it for my usecase.

**Comment by Angr1st** [comment]
Small update I found [this](https://github.com/JasperFx/lamar) which allowed me to do the dynamic stuff that I wanted have a look [here](https://github.com/Angr1st/TinyCsvToElasticsearch). My only problem is that i need to call .any() on the ParallelQuery<T> otherwise i get an exception that reading from a closed TextReader is not allowed. Would you know a reason why a ParallelQuery would act this way?

**Comment by bytefish** [comment]
Dynamic Mappings would be a great feature, but I am lacking the resources to implement it in the near future. Right now I prefer to have the library with fixed mappings. For sophisticated mappings people will turn to CsvHelpers anyway. This library is optimized for speed, so maybe this is what it should be known for.

I don't want to generate false expectations, like users can expect me to support dynamic mappings sometime soon. So I am closing this issue.

Sorry! 🙏

**Comment by Angr1st** [comment]
Just a small heads up I got help from the elasticsearch guys and got it working. Thank you again for writing this Lib!

**Comment by bytefish** [comment]
Cool! Thanks for the feedback and honestly sorry for not putting more effort into it.

**Comment by Angr1st** [comment]
No worries! Doing one thing extremly well should be enough to strife for!

Philipp Wagner <notifications@github.com> schrieb am Mo., 16. Sep. 2019,
06:20:

**Comment by bryanrideshark** [comment]
@bytefish you had it EXACTLY right with your dynamic mapping. Thanks for the sample, wish you had kept it around somewhere, but I love how simple that API is. Keeps the speed, and keeps the flexibility.

You did good!

**Comment by bytefish** [comment]
@bryanrideshark Thanks for the kind words!
