### ISSUE TITLE
How to read/handle linebreaks in a field

### ISSUE THREAD

**Issue by pratikpj13** [bytefish/TinyCsvParser#29]
Hello TinyCsvParser team,

I am using this package in my .Net Core application to read CSV files. Everything works well in all scenarios except one. 

Sometimes, I get value of a column with line breaks and TinyCSVParser cannot identify it and throws Out of Range Error.  I am using CSVParser object's ReadFromFile() method. Is there any solution available to read linebreaks in a field? 

I am very thankful to the team who developed and released TinyCsvParser for public.

I think this issue has already been marked as "3.0 Enhancement"  however I just want to confirm. Also, let me know if there is any short term fix for this until 3.0 is released? Otherwise I would hate to switch over to another CSV Parser in my code.

Thanks,
Pratik

**Comment by bytefish** [comment]
Sadly no, there won't be a quick fix. I think you have to switch the CSV Parser, if multiline parsing is a requirement in your situation. CsvHelper contains a great multiline parser implementation:

* [https://github.com/JoshClose/CsvHelper/](https://github.com/JoshClose/CsvHelper/)

The current implementation of TinyCsvParser is optimized on speed and does a simple ``File.ReadLines`` in its current implementation. Using a more complex parser would mean a rework of the current processing pipeline, which I do not have the time for right now.

**Comment by bytefish** [comment]
Closed as a duplicate to Issue #26.

**Comment by pratikpj13** [comment]
Thank you for the response. Yes, as you suggested, I replaced with CsvHelper and it worked the way I expected with linebrakes in a field.

**Comment by bytefish** [comment]
Great! Good luck with your project.
