### ISSUE TITLE
Get List<T> from List<TinyCsvParser.Mapping.CsvMappingResult<T>>

### ISSUE THREAD

**Issue by JwanKhalaf** [bytefish/TinyCsvParser#31]
I have the following simple code:

![image](https://user-images.githubusercontent.com/42877376/48195094-9ada1700-e346-11e8-9a65-50d10235ac22.png)

What is the recommended way of getting at the underlying type?

Right now my result is:

`List<TinyCsvParser.Mapping.CsvMappingResult<ShippingRecord>>` but I am after `List<ShippingRecord>`.

I know I can loop and create a new list and return that, but is that the recommended way here? There's no easier way?

**Comment by bytefish** [comment]
csvParser
    // Read the File:
    .ReadFromFile(csvFilePath, Encoding.UTF8)
    // Get the Valid Results:
    .Where(x => x.IsValid)
    // And get the populated Entities:
    .Select(x => x.Result)
    // Turn it into a List:
    .ToList();
