### ISSUE TITLE
NumberStyles.AllowThousands on by default in DoubleConverter but not Int32Converter

### ISSUE THREAD

**Issue by tpdickson** [bytefish/TinyCsvParser#32]
Hi, what is the reason for having the AllowThousands flag enabled in DoubleConverter but not enabled in Int32Converter by default?

I'm going to enable it on a custom TypeConverter, just bringing this to your attention in case the difference isn't intentional. Thanks

**Comment by bytefish** [comment]
I think I wanted to use the defaults, that are used by the .NET Framework. I will check this, thanks for the issue.

**Comment by bytefish** [comment]
It's because .NET does not use AllowThousands on a call to ``Parse``:

* https://referencesource.microsoft.com/#mscorlib/system/int32.cs,a438016f815a35c3
