### ISSUE TITLE
parsing error when last column is empty

### ISSUE THREAD

**Issue by stevengopmo** [bytefish/TinyCsvParser#34]
hello I have a file where a small number of records are "missing" a value in the last column.  The file is tab delimited and the last tab is there but the parser still gives an error.  For example
`abc\ t0.00 \t 0.00 \t 0.00 \t 0.00 \t 0.00 \t 0.00 \t 0.00 \t 0.00 \t 0.00 \t`
(I added spaces to be a little clearer).  

Most of the time the last column has a value (xx or yy) but in these (valid) cases the value is an empty string.  Is there a configuration option of this scenario or do I need to do via pre-processing or custom tokenizer?  I hate to do this for such a small population of records but the empty string *is* valid.

**Comment by bytefish** [comment]
@stevengopmo Thanks for filing the issue. Can you provide a small unit test to show the expected and the actual results? Maybe there is a problem with the Parser.

**Comment by stevengopmo** [comment]
actually I figured this out.  I had the following as my settings

` var tokenizer = new StringSplitTokenizer(new[] { Delimiter }, trimLine: true);`

changing trimLine to false fixed it

**Comment by stevengopmo** [comment]
maybe this could be updated somewhere in the documentation?

**Comment by bytefish** [comment]
I will add it!

**Comment by bytefish** [comment]
I thought about it while driving and it is a bug. The line shouldn't be trimmed, before it is split into tokens. I fill fix this and release a new version. Meanwhile you can use the workaround you described.

**Comment by stevengopmo** [comment]
excellent, I agree it does seem like a bug as I probably only really want to trim column values not the record, but my work around works until then I think.

**Comment by bytefish** [comment]
I have released Version 2.1.0 to NuGet, which fixes this issue. It should be available as soon the NuGet Server indexes the packages. Please reopen, if the problem persists. 👍

**Comment by stevengopmo** [comment]
got the updated lib and works perfectly.  thank you

**Comment by bytefish** [comment]
Great! Thanks for the feedback. 🙃
