### ISSUE TITLE
Parsing to string fails if field contains a newline character

### ISSUE THREAD

**Issue by tpdickson** [bytefish/TinyCsvParser#35]
I have a string field wrapped by quotes that contains a newline:

"This is a 
test value"

And it seems to be failing to parse it correctly to a string type, causing it to be null / !IsValid. It also seems to cause additional lines to be parsed (it takes the line with the newline character and creates another line with it). These lines also are not valid, as expected.

The csv file is displayed without issue in Excel. Is there a way to handle this properly in TinyCsvParser without modifying the string value of the field, or is it a bug where it's not checking if a quote " is open before moving to the next line to try and parse?

Thanks

**Comment by tpdickson** [comment]
This might be a pain to actually fix, since it seems the file is being split up front on newline characters.

I might have to read through the entire file beforehand character by character and keep track of quotation state, then replace any newlines in OPEN state with another character.

**Comment by bytefish** [comment]
Yes, this is a limitation of the Parser see Issue #26. I started a 3.0 Branch, an maybe I add a Tokenizer, that handles Newlines. But I cannot give a Timeline right now.

I am closing this as a duplicate.
