### ISSUE TITLE
 MapProperty(6, x => x.Amount, new DecimalConverter(new CultureInfo("nl-NL")));

### ISSUE THREAD

**Issue by comn-nl** [bytefish/TinyCsvParser#44]
The line:  
MapProperty(6, x => x.Amount, new DecimalConverter(new CultureInfo("nl-NL"))); 

gives an error: 
The type arguments for method cannot be inferred from the usage. Try specifying the type arguments explicitly.

 I would like to use the DecimalConverter to parse a csv with a , instead of a . as a decimal separator

**Comment by bytefish** [comment]
What type is the property "Amount"?

**Comment by comn-nl** [comment]
Thanks for your quick response. I am sorry for missing this. I made a mistake in the class itself. So stupid.

**Comment by bytefish** [comment]
No worries! 😎
