### ISSUE TITLE
Not a member access Parameter name: expression'

### ISSUE THREAD

**Issue by KSingh1980** [bytefish/TinyCsvParser#45]
Getting this error while reading the CSV File ..Not a member access
Parameter name: expression'

**Comment by bytefish** [comment]
Where does the error happen? It looks like there is a problem in your CsvMapping. Please provide sufficient information to reproduce the problem.

**Comment by KSingh1980** [comment]
I found the issue, I was using 
  MapProperty(0, x => x.File_Number.**trim()**);

The method trim() was causing the issue as I have File_Number as string type. I guess, it was considering the whole thing as an attribute and failing in reflection code somewhere.

I am not sure if it should work or not but I removed the method trim() and it works.

**Comment by bytefish** [comment]
Great you found the Issue! Yes, the parameter you pass into MapProperty must be pointing to a Property. 👍
