### ISSUE TITLE
Allow Custom Tokenizers for parsing the Input

### ISSUE THREAD

**Issue by bytefish** [bytefish/TinyCsvParser#5]
At the moment the ``CsvParser`` uses a fixed ``string.Split(...)`` to split a given line into an array of strings, the columns so to say. 

This might not be appropriate in more complex scenarios (see Issue #4). One way to handle complex data is to preprocess it, so it can be easily parsed by the current ``CsvParser`` (as done in Issue #4).

It is probably more useful to allow configuring the split routine (currently a simple ``string.Split(...)``) with a more complex routine, for example similar to the one used in Issue #4.

The following lines would have to be modified:

![image](https://cloud.githubusercontent.com/assets/239373/12057477/bdfc30ba-af41-11e5-827f-8f7b18c71d96.png)

**Comment by bytefish** [comment]
This Issue was resolved with Commit: 5455f810f83b64a4af29efa7cce66416ca8108ff. Sample Tokenizers have been added and allow more flexibility when parsing the Input.

**Comment by murilowlima** [comment]
Works like a charm!

**Comment by bytefish** [comment]
Awesome. Thanks for the Feedback!
