### ISSUE TITLE
getting details about parsing errors

### ISSUE THREAD

**Issue by thdotnet** [bytefish/TinyCsvParser#50]
Hi,

how to get details about a conversion error or missing column when parsing the csv file? We only have IsValid property, but is there a way to capture what was the real error? (e.g when you have a row with more than 20 fields, sometimes it's hard to identify the problem.)

**Comment by bytefish** [comment]
If the IsValid Property is false, then the Error is populated. Does it give you a better insight to problems? 🤔

**Comment by bytefish** [comment]
Please feel free to discuss although I closed the ticket.
