### ISSUE TITLE
Dynamic mapping based on number of columns...

### ISSUE THREAD

**Issue by cbwilliamsnh** [bytefish/TinyCsvParser#53]
I have a situation where I need to be able to parse files that may have a different number of columns.
 
Sidebar: I have a CSV file format specification that has changed over time by the addition of columns. For example, I may have a file that arrives with 76 columns and another with 112 columns. The first 76 columns of the 112 column file are identical (i.e. column 8 will always be email address and column 65 will always be system id.)
 
So I want to be able to write one parser that can handle both files, that is, if I have 112 columns I can map data in those columns and if it only has 76 columns my parser won’t fail. Can this be done with TinyCsvParser?
 
Thank you in advance

**Comment by bytefish** [comment]
I tried my best to come up with a prototype on how to do it. But how I initially designed the processing pipeline is probably flawed and makes it complicated to hook into it.

![image](https://user-images.githubusercontent.com/239373/62818702-0279f880-bb4b-11e9-87d4-cea835799695.png)

So no, at the moment it is not supported.

I am sure CsvHelper is better suited for this use-case and also supports .NET Core:

* https://joshclose.github.io/CsvHelper/

Sorry for the inconvenience. If I could redesign the library for a 3.0, it would probably look different.

**Comment by cbwilliamsnh** [comment]
Philipp,

I was able to switch to CsvHelper. The library has a setting that ignores mappings that aren't found or cause exceptions.

Chuck

________________________________

**Comment by bytefish** [comment]
Great! Good luck with your project. 🤗
