### ISSUE TITLE
201503hourly.txt file missing

### ISSUE THREAD

**Issue by dariogriffo** [bytefish/TinyCsvParser#55]
I'm trying to run locally the benchmark tool and the file is not part of the repository.
Can you upload it somewhere, make it public?

**Comment by dariogriffo** [comment]
I found the link in the docs, but the markup is incorrect, can you please fix it?
This is the link in the docs
http://www.ncdc.noaa.gov/orders/qclcd](http://www.ncdc.noaa.gov/orders/qclcd
It should be
http://www.ncdc.noaa.gov/orders/qclcd

**Comment by bytefish** [comment]
Where in the docs? Could you send me a link, so I can correct it? 👍
