### ISSUE TITLE
Async methods to read files

### ISSUE THREAD

**Issue by dariogriffo** [bytefish/TinyCsvParser#56]
I have created a new method to parse the file with an async method, added unit testing and ran benchmark.
The results are mixed (time doubles, but memory consumption is extremely low)
Would you consider a PR for this? I'm in the middle of a development that requires parsing files of 2.5Gb+ on a background service that executes every day, and time is not a constraint, but memory is.

Here is an screenshot of the benchmark

![2019-09-24_1154](https://user-images.githubusercontent.com/3247183/65501975-3a05ef80-dec2-11e9-9a6b-1b81ba521c1d.png)

And the implementation, looks something like this.

    public static class CsvParserExtensions
    {
        public static async Task<ParallelQuery<CsvMappingResult<TEntity>>> ReadFromFileAsync<TEntity>(this CsvParser<TEntity> csvParser, string fileName, Encoding encoding)
        {
    	if (fileName == null)
    	{
    	    throw new ArgumentNullException(nameof(fileName));
    	}	
	
    	var lines = new List<Row>();
    	var index = 0;
    	using (var stream = new StreamReader(File.Open(fileName, FileMode.Open), encoding))
    	{
    	    while (!stream.EndOfStream)
    	    {
                    var line = await stream.ReadLineAsync();
    		lines.Add(new Row(index++, line));
                }
            }
    	return csvParser.Parse(lines);
        }    
    }

**Comment by bytefish** [comment]
You are accumulating all data in a list, of course this consumes too much memory.

See the Parser returns an ``Enumerable``, so you can iterate the result without evaluating the list completely. You can use for example a for-each for iterating through the results of the Parse(...) method.

Thanks for the addition and please do not take it personal, but I will not include it.

**Comment by nawfalhasan** [comment]
> See the Parser returns an Enumerable, so you can iterate the result without evaluating the list completely

But that's not what async is for. I wished there is a IAsyncEnumerable options as well
