### ISSUE TITLE
Mapping raw line?

### ISSUE THREAD

**Issue by skacurt** [bytefish/TinyCsvParser#57]
Hi,

I'm in the middle of writing a utility that sorts huge CSV files, so wanted to use this library to parse files. During the sort process, although there are many fields in the CSV file, only the field to be used for sorting and the raw line is required.

So the question is, in addition to regular mappings, is there a built-in way to get the raw line? `CsvMappingResult<TEntity>` doesn't provide anything similar. 

What would you suggest to accomplish this "raw line" task with TinyCsvParser?

The following was my first _-and failed of course-_ attempt 😅. 
I think I was thinking that handling `-1` to map whole line would be the good for the parser's non greedy approach.

```cs

class CsvLine
{
	public int SortValue { get; set; }
	public string RawLine { get; set; }
}

class CsvLineMapping : CsvMapping<CsvLine>
{
	public CsvLineMapping(int sortColumnIndex) : base()
	{
		MapProperty(-1, x => x.RawLine); // -1 for the raw line?
		MapProperty(sortColumnIndex, x => x.SortValue);
	}
}

```

**Comment by skacurt** [comment]
Congratulations dad 😀 No worries. Then I'm closing the issue. Already following the project, so I'll be notified when there's a new release. Good luck!

**Comment by bytefish** [comment]
Thanks for your understanding! 😎
