### ISSUE TITLE
Questions about removing Linq.Expressions

### ISSUE THREAD

**Issue by laicasaane** [bytefish/TinyCsvParser#59]
Hi @bytefish,

I'm currently using this library in a Unity project. And because Unity' [IL2CPP compiler currently cannot handle expressions with value type arguments](https://forum.unity.com/threads/are-c-expression-trees-or-ilgenerator-allowed-on-ios.489498/#post-3665089), this library cannot run on AOT platforms. So I want to replace Linq.Expressions with explicit delegates.

Since this is a platform specific issue and it seems so far only me have encountered this problem, so I intend to make a fork and do it myself. However, I would like to know your opinions on this matter first: Is it possible removing Linq.Expressions in the current code base? Or will it become complicated if we use explicit delegates?

**Comment by bytefish** [comment]
I think we can also use a normal ``Func`` lambda function as a
property accessor. The only thing, that's going to be missing then is the Property Name as far as I can see. Would that resolve the problem?

**Comment by laicasaane** [comment]
Is the Property Name essential in some cases? So far I haven't met any use case which requires Property Name.

**Comment by bytefish** [comment]
Well, it is stored in the mapping I think and it might be useful for debugging. But I also don't think it is that important. If you feel like you could give it a try and make a PR. I won't be able to implement it the days ahead.

**Comment by bytefish** [comment]
Now I see the Property Name is even private:

* https://github.com/bytefish/TinyCsvParser/blob/master/TinyCsvParser/TinyCsvParser/Mapping/CsvPropertyMapping.cs

So replacing the Expression with a normal ``Func`` isn't even a breaking change.

**Comment by laicasaane** [comment]
Alright. I'll start working on this. Thanks for your support :)

**Comment by laicasaane** [comment]
I've made a build test and found out that `System.Linq.Parallel` too doesn't work well with IL2CPP.

**Comment by laicasaane** [comment]
Just let you know that I've managed to remove System.Linq and Expressions. Now it works perfectly with IL2CPP 😃

**Comment by bytefish** [comment]
@laicasaane Sounds good! Good luck with the project. 🙏
