### ISSUE TITLE
TinCsvParser adding a comma at the end

### ISSUE THREAD

**Issue by zoinkydoink** [bytefish/TinyCsvParser#60]
I have the following

Johnson|Anne|110236|697125|1.00|Teacher|js@someemail.org
when its read and parsed, the email field on my object contains "js@someemail.org,"
I am not sure where this extra comma is coming from but it is not in my data
here is how i am reading it

```
CsvParserOptions csvParserOptions = new CsvParserOptions(true, '|');
ImportTeachersDataMapping csvMapper = new ImportTeachersDataMapping();

CsvParser<TeacherSourceData> csvParser = new CsvParser<TeacherSourceData>(csvParserOptions, csvMapper);

var all = csvParser
    .ReadFromFile(request.FilePath, Encoding.UTF8)                
    .ToList();
```

**Comment by bytefish** [comment]
I will take a look at it!

**Comment by bytefish** [comment]
@zoinkydoink I have added a Unit Test, that tries to reproduce the issue. The test doesn't fail and parses the line as expected, so I don't see a trailing comma coming back from CSV parsing with TinyCsvParser. 

If you manage to reproduce the issue with this test, please let me know. 

The test is here:

* https://github.com/bytefish/TinyCsvParser/blob/master/TinyCsvParser/TinyCsvParser.Test/Issues/Issue60_TrailingComma.cs

**Comment by zoinkydoink** [comment]
My apologies, it seems that the problem is on my end (some how comma's got saved to my file opening and saving in excel).

Consider this issue closed and again I am sorry for reporting a non bug

**Comment by bytefish** [comment]
No worries! Thanks for filing the issue. 👍
