### ISSUE TITLE
Where is the benchmark test data?

### ISSUE THREAD

**Issue by bickycheese** [bytefish/TinyCsvParser#64]
Hi,

Having big [discrepancies](https://github.com/dotnet/BenchmarkDotNet/issues/1450) between using this library during benchmarking in Windows and Linux.
So decided to run benchmarks for this project but it seems that the test file is not pushed to the repo?
`G:\Datasets\QCLCD\201503hourly.txt`

Kr,

Stan

**Comment by bytefish** [comment]
I will add the file.

**Comment by bytefish** [comment]
Sorry, I cannot add the file. It is zipped around 70 MB. This is a bit too heavy for GitHub. That's why I marked the Test as Ignored. What we could do instead, and this is what I will do now... Is to add a small method, that creates a temporary CSV file for the Benchmark.

**Comment by bickycheese** [comment]
> 
> 
> Sorry, I cannot add the file. It is zipped around 70 MB. This is a bit too heavy for GitHub. That's why I marked the Test as Ignored. What we could do instead, and this is what I will do now... Is to add a small method, that creates a temporary CSV file for the Benchmark.

I guessed that much, a method will do fine. ;)

**Comment by bytefish** [comment]
I have added the routine. Please note it creates a file with 669 MB, which doesn't match the original data... but it serves as a nice performance test I guess. :-)
