### ISSUE TITLE
Convert decimal comma notation to dot in mapper

### ISSUE THREAD

**Issue by ErnieBernie10** [bytefish/TinyCsvParser#69]
The CSV I am working with has decimal numbers in comma notation. Is there a way to convert the comma into a dot when doing the property mapping? My code currently looks like this:

```C#
        public CsvArticleMapping() : base()
        {
            ...
            MapProperty(4, x => x.ListPrice); // This line is in comma notation and should be converted
            ...
        }
```

When using this code the parser simply ignores the comma and reads the number as an integer.

**Comment by bytefish** [comment]
You need to use a ``DecimalConverter`` and pass  the Localization or NumberFormat you want to use, like described for a Boolean here: 

* http://bytefish.github.io/TinyCsvParser/sections/tutorials/custom_formats.html#tutorials-custom-formats

**Comment by ErnieBernie10** [comment]
I changed it to this:

```C#
MapProperty(4, x => x.ListPrice, new DoubleConverter(new CultureInfo("en-US"));
```

But getting the message:

 ``Argument 3: cannot convert from 'TinyCsvParser.TypeConverter.DoubleConverter' to 'TinyCsvParser.TypeConverter.IArrayTypeConverter<double?>'
``

I'm really don't know why I'm having so much trouble understanding this.

**Comment by bytefish** [comment]
Could you make a minimal example? What type is the property ``ListPrice``?

**Comment by ErnieBernie10** [comment]
```c#
public double? ListPrice { get; set; }
```

This is the property I'm trying to map to.

The value I get from the CSV looks like this: ``123,45``

After parsing without a converter I get ``12345`` from the mapping

And I can't get the converter to work.

**Comment by bytefish** [comment]
It's a ``double?`` so you have to use a ``NullableDoubleConverter``. 

Here is a full example:

```csharp
using NUnit.Framework;
using System;
using System.Globalization;
using System.Linq;
using System.Text;
using TinyCsvParser.Mapping;
using TinyCsvParser.TypeConverter;

namespace TinyCsvParser.Test.CsvParser
{
    [TestFixture]
    public class DoubleConverterTest
    {
        private class Entity
        {
            public double? Value { get; set; }
        }

        private class CsvEntityMapping : CsvMapping<Entity>
        {
            public CsvEntityMapping()
            {
                MapProperty(0, x => x.Value, new NullableDoubleConverter(new CultureInfo("de-DE")));
            }
        }

        [Test]
        public void ParseWithNULLStringTest()
        {
            CsvParserOptions csvParserOptions = new CsvParserOptions(false,  ';');
            CsvReaderOptions csvReaderOptions = new CsvReaderOptions(new[] { Environment.NewLine });
            CsvEntityMapping csvMapper = new CsvEntityMapping();
            CsvParser<Entity> csvParser = new CsvParser<Entity>(csvParserOptions, csvMapper);

            var stringBuilder = new StringBuilder()
                .AppendLine("123,456");

            var result = csvParser
                .ReadFromString(csvReaderOptions, stringBuilder.ToString())
                .ToList();

            Assert.AreEqual(123.456, result[0].Result.Value);
        }
    }
}
```

**Comment by ErnieBernie10** [comment]
That fixed the issue. I didn't realize there was a nullable converter. Thanks!
