### ISSUE TITLE
Parse rows as columns and vice versa

### ISSUE THREAD

**Issue by laicasaane** [bytefish/TinyCsvParser#70]
Please consider adding the ability to parse rows as columns.

My current problem is: I have a configuration csv which contains only 1 row, but multiple columns which will be mapped into multiple property. However, the number of columns is quite large and it makes the Excel sheet too long horizontally so it's hard to view all the config fields at once. Some column names are also quite long too, which adds to the problem.

That's why I'd like to make the config fields rows rather than columns.

**Comment by bytefish** [comment]
I cannot imagine what the data looks like. Is it like This:

```
Prop A, Prop B,, Prop A, Prop B, ...
```

Then I would do something like this:

```csharp
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using TinyCsvParser.Mapping;
using TinyCsvParser.Model;

namespace TinyCsvParser.Test.Examples
{
    public static class EnumerableExtensions
    {
        public static IEnumerable<IEnumerable<T>> Batch<T>(this IEnumerable<T> source, int size)
        {
            T[] bucket = null;
            var count = 0;

            foreach (var item in source)
            {
                if (bucket == null)
                {
                    bucket = new T[size];
                }

                bucket[count++] = item;

                if (count != size)
                {
                    continue;
                }

                yield return bucket.Select(x => x);

                bucket = null;
                count = 0;
            }

            if (bucket != null && count > 0)
            {
                yield return bucket.Take(count);
            }
        }
    }

    public class RowBasedCsvParser<TEntity>
    {
        private readonly CsvParserOptions options;
        private readonly ICsvMapping<TEntity> mapping;

        public RowBasedCsvParser(CsvParserOptions options, ICsvMapping<TEntity> mapping)
        {
            this.options = options;
            this.mapping = mapping;
        }

        public IEnumerable<CsvMappingResult<TEntity>> Parse(string rowData, int numberOfProperties)
        {
            if (rowData == null)
            {
                throw new ArgumentNullException(nameof(rowData));
            }

            // This could be too huge for In-Memory. Maybe optimize it, so you 
            // are using IEnumerable:
            var tokens = options.Tokenizer.Tokenize(rowData);

            return tokens
                // Now we Batch the Columns into smaller groups, so they resemble a Row:
                .Batch(numberOfProperties)
                .Select((x, i) => new TokenizedRow(i * numberOfProperties, x.ToArray()))
                .Select(x => mapping.Map(x));
        }

        public override string ToString()
        {
            return $"CsvParser (Options = {options})";
        }
    }

    // Test Entities
    public class TestEntityForRow
    {
        public string A { get; set; }

        public string B { get; set; }
    }

    public class TestEntityForRowMapper : CsvMapping<TestEntityForRow>
    {
        public TestEntityForRowMapper()
        {
            MapProperty(0, x => x.A);
            MapProperty(1, x => x.B);
        }
    }

    [TestFixture]
    public class RowParseTest
    {
        [Test]
        public void TestCustomRowParser()
        {
            string csvRowTestData = "1,2,3,4,5,6,7,8";

            var csvParserOptions = new CsvParserOptions(true, ',');
            var csvReaderOptions = new CsvReaderOptions(new[] { Environment.NewLine });
            var csvMapper = new TestEntityForRowMapper();
            var csvParser = new RowBasedCsvParser<TestEntityForRow>(csvParserOptions, csvMapper);

            var res = csvParser
                .Parse(csvRowTestData, 2)
                .Where(x => x.IsValid)
                .ToList();

            Assert.AreEqual(4, res.Count);

            Assert.AreEqual("1", res[0].Result.A);
            Assert.AreEqual("2", res[0].Result.B);
        }
    }
}
```

**Comment by laicasaane** [comment]
If there is an option to parse rows as columns, then my data will look like below

```
config,value
resolution_width,1920
resolution_height,1080
music_fade_time,1
inner_grid_rows,4
inner_grid_columns,3
outer_grid_rows,5
outer_grid_columns,4
wait_before_battle,1
wait_before_endless,2
```

**Comment by bytefish** [comment]
And the original data looks like this?

``resolution_width,1920,,resolution_height,1080,,music_fade_time,1,seconds,inner_grid_rows,4,,inner_grid_columns,3,,outer_grid_ros,5,,outer_grid_columns,4,,wait_before_battle,1,seconds,wait_before_survival,2,seconds,``

**Comment by laicasaane** [comment]
No my example is the original data.

**Comment by bytefish** [comment]
Ah ok, because you said your data is 1 row. Sorry, then I misunderstood the problem.

**Comment by bytefish** [comment]
And what will the C# class you map to look like?

**Comment by laicasaane** [comment]
Yes, with the current functionality, I must arrange my data by columns:

```
config_property,resolution_width,resolution_height,music_fade_time,inner_grid_rows,inner_grid_columns,outer_grid_rows,outer_grid_columns,wait_before_battle,wait_before_survival,
config_value,1920,1080,1,4,3,5,4,1,2,
config_unit,,,seconds,,,,,seconds,seconds,
```

But this make the sheet stretched too long horizontally. So I want to arrange the data by rows, as in https://github.com/bytefish/TinyCsvParser/issues/70#issuecomment-683056376

C# class map should be the same. The tokenizer should remap rows to columns and columns to rows without users have to change their class maps.

**Comment by bytefish** [comment]
Understood. Give me some time to come up with something.

**Comment by laicasaane** [comment]
I've also been thinking a solution for this right after posting this issue. I'm intending to do the row to column remapping right after this line https://github.com/bytefish/TinyCsvParser/blob/af039ef132047ee4f1dd8139b05f3bfb1c70ff6b/TinyCsvParser/TinyCsvParser/CsvParser.cs#L51

But then I have to introduce another option to ignore the first column (same as skipHeader), and I have to check for comment character. It seems to be complicated.

**Comment by laicasaane** [comment]
How about we do the tokenization for every raw line first, and save those tokens in a kind of 2D array. Then we can choose how to map that 2D array the way we want, by columns or by rows?

**Comment by bytefish** [comment]
This sounds a little complicated and I would rather not introduce this. Isn't there a way to automatically rearrange the data the way you need it for processing?

**Comment by laicasaane** [comment]
Thanks for your time. I know this is quite complicated and maybe only my special use case. So I'm going to write another parser for it rather than modifying the existing one.

**Comment by bytefish** [comment]
@laicasaane Thanks for your understanding and I am sorry, I am not much more of a help.
