### ISSUE TITLE
Issue when reading quoted fields containing the delimeter

### ISSUE THREAD

**Issue by JeremySkinner** [bytefish/TinyCsvParser#8]
I ran into an issue with TinyCsvParser today. It's possible for a field within a CSV file to contain the delimeter character, without being used as a delimter, if the field value contains quotes. Eg:

id,name,amount
12345, "John, Dave and Bryan", 23

TinyCsvParser doesn't seem to handle this- it thinks John is the end of the second field, when actually it should read until the end of the double quotes.

**Comment by bytefish** [comment]
Hi Jeremy,

This case can be handled with a QuotedStringTokenizer. Please see the documentation at: http://bytefish.github.io/TinyCsvParser/sections/userguide/tokenizer.html#quotedstringtokenizer

Please let me know, if this resolves the issue.

**Comment by JeremySkinner** [comment]
Brilliant! Thanks.

**Comment by bytefish** [comment]
Great!
