### ISSUE TITLE
QuotedStringTokenizer to ignore "escaped" delimiters

### ISSUE THREAD

**Issue by jsancho** [bytefish/TinyCsvParser#9]
I am trying to parse a csv that uses double quotes as a delimiter of text fields.
When a column includes a literal double quote, it is escaped with a repetition of the double-quote itself.

For example:
Name, Age, Description
"Robert, Willis", 36, "All-around nice guy who always says hi"
"Michael, Chester", 24, "Also goes by ""Mike"", among friends that is"

The idea is that the parsed description column should include the quotes  in the result 
-> Also goes by "Mike", among friends that is"

If using the QuotedStringTokenizer, these text fields will fail to parse correctly.
I've been trying to modify the regex inside the class QST, but I'm afraid that I'm not that good at regexing.

Could you maybe share some tips on how to parse escaped/doubled delimiter symbols?

**Comment by jsancho** [comment]
Just reading more into this, now I see that the escaping double quotes with an additional double quote is what's suggested in the IETF RFC4180

https://tools.ietf.org/html/rfc4180#section-2

So it would definitely be helpful to have this functionality as part of the standard QuotedStringTokenizer behaviour.

**Comment by bytefish** [comment]
Hi Jaume,

Thanks for your valuable informations! :+1:

This week is a little packed with work. I will look into it this weekend and come up with something. :-)

Thanks again, Philipp.

**Comment by bytefish** [comment]
Here is a great discussion on parsing the data:

* http://programmers.stackexchange.com/questions/166454/can-the-csv-format-be-defined-by-a-regex

**Comment by bytefish** [comment]
Apache Commons-CSV goes great lengths to support an RFC4180-compliant parser. Probably a Regular Expression is not sufficient, I will investigate it further. The Apache Commons-CSV Lexer is interesting anyway:

* https://github.com/apache/commons-csv/blob/trunk/src/main/java/org/apache/commons/csv/Lexer.java

**Comment by jsancho** [comment]
wow, thanks very much for getting on top of this so quickly.
I've come across some of the same SO answers suggesting that the regex is a rather tough battle to fight for this.
I'll check out the Apache Commons-CSV, that might have some interesting insight.

**Comment by bytefish** [comment]
I would start writing a simplified version of the Lexer this weekend. I don't think a Regular Expression is sufficient (plus I am not good with Regular Expression either... the one in the Tokenizer was a mix of 5 SO posts 😳).

We will see how it fits into the existing processing pipeline, I hope it works without too many changes to the core.

**Comment by bytefish** [comment]
I have created a new branch rfc4180, which will deal with this Issue.

**Comment by bytefish** [comment]
I have added an initial version, but it still resembles the Apache Parser too much and I don't think it is fully RFC4180-compliant. The Unit Test with your Test Data works correctly, but I have yet to add some corner cases and I didn't look into UTF8 characters yet.

**Comment by bytefish** [comment]
Added a reworked RFC4180 parser as of commit cdd4fd0, which makes no use of Apache Commons code. The Code is also simpler to read. It will be merged to the trunk as soon as I have written some more test cases.

**Comment by jsancho** [comment]
Hi Philipp, thanks so much for the quick turnaround.
what an effort!

I've pulled the new branch and tried to get my csv samples through the parser, but I'm finding  some issues with columns reportedly being "Out of Range".

Is this how you would expect me to invoke the new functionality?

var csvParserOptions = new CsvParserOptions(skipHeader: true, commentCharacter: string.Empty,
                    tokenizer: new RFC4180Tokenizer(new Options('"', '\\', ',')));

thanks again.
ps: I could also put together a sample test file to help out with debugging.

**Comment by bytefish** [comment]
Hi Jaume,

Could you send me some sample data, that is failing for you? So I can write
unit tests and fix the eventual bugs.

Thanks!

**Comment by jsancho** [comment]
Absolutely, let me get a simple project together, so you can test it out yourself.

Thanks a million mate

**Comment by jsancho** [comment]
Hi Philipp, 

Finally managed to get to the end of this.

The issue is that the new RFC4180Tokenizer is that doesn't like empty fields.
Whenever a column is empty, the parser will throw a "Column X Out of Range", with "x" being the column following the empty one.

For example.

Name, Age, Description
"Robert, Willis", 36, "All-around nice guy who always says hi"
"Robert, Willliamson", , "All-around nice guy who always says hi"
"Robert, Wilkinson", , "All-around nice guy who always says hi"

Will throw a "Column 2 out of range" when trying to parse the 3rd row, as it has no age value.

This works as expected when using QuotedStringTokenizer, i.e. the value is left empty.

thanks

**Comment by bytefish** [comment]
Thanks for the sample data. I will look into it next weekend.

**Comment by jsancho** [comment]
amazing, thanks again :)

**Comment by bytefish** [comment]
Hi Jaume,

I have fixed the RFC4180Tokenizer, added a Test Case and merged it into the master.

Here is an example for using it:

```csharp
// Copyright (c) Philipp Wagner. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using NUnit.Framework;
using System;
using System.Linq;
using System.Text;
using TinyCsvParser.Mapping;
using TinyCsvParser.Tokenizer.RFC4180;

namespace TinyCsvParser.Test.Tokenizer
{
	[TestFixture]
	public class Rfc4180TokenizerTest
	{
		private class SampleEntity
		{
			public string Name { get; set; }

			public int? Age { get; set; }

			public string Description { get; set; }
		}

		private class SampleEntityMapping : CsvMapping<SampleEntity>
		{
			public SampleEntityMapping()
			{
				MapProperty(0, x => x.Name);
				MapProperty(1, x => x.Age);
				MapProperty(2, x => x.Description);
			}
		}

		[Test]
		public void RFC4180_CsvParser_Integration_Test()
		{
			// Use a " as Quote Character, a \\ as Escape Character and a , as Delimiter.
			var options = new Options('"', '\\', ',');

			// Initialize the Rfc4180 Tokenizer:
			var tokenizer = new RFC4180Tokenizer(options);

			// Now Build the Parser:
			CsvParserOptions csvParserOptions = new CsvParserOptions(true, tokenizer);
			SampleEntityMapping csvMapper = new SampleEntityMapping();
			CsvParser<SampleEntity> csvParser = new CsvParser<SampleEntity>(csvParserOptions, csvMapper);


			var stringBuilder = new StringBuilder()
				.AppendLine("Name, Age, Description")
				.AppendLine("\"Michael, Chester\",24,\"Also goes by \"\"Mike\"\", among friends that is\"")
				.AppendLine("\"Robert, Willliamson\", , \"All-around nice guy who always says hi\"");
			
			// Define the NewLine Character to split at:
			CsvReaderOptions csvReaderOptions = new CsvReaderOptions(new[] { Environment.NewLine });

			var result = csvParser
				.ReadFromString(csvReaderOptions, stringBuilder.ToString())
				.ToList();

			Assert.AreEqual(2, result.Count);

			Assert.AreEqual(true, result.All(x => x.IsValid));

			Assert.AreEqual("Michael, Chester", result[0].Result.Name);
			Assert.AreEqual(24, result[0].Result.Age);
			Assert.AreEqual("Also goes by \"Mike\", among friends that is", result[0].Result.Description);

			Assert.AreEqual("Robert, Willliamson", result[1].Result.Name);
			Assert.AreEqual(false, result[1].Result.Age.HasValue);
			Assert.AreEqual("All-around nice guy who always says hi", result[1].Result.Description);
		}
	}
}
```

**Comment by bytefish** [comment]
Please let me know, if it resolves the problems in your current project.

**Comment by jsancho** [comment]
No, thank you for all your hard work!

We're almost there, but there is still one remaining issue to parse the files that I'm trying to import.
If the last column of a csv row is empty the "column out of range error" will still get thrown.
Said the other way around, empty fields are successfully ignored, unless it's the last column is the empty one.

With that little niggle fixed, we'd be feature complete from my end :)

**Comment by bytefish** [comment]
Well, it should be fixed. I should really flex my skills writing more complex Lexers. :-)

**Comment by jsancho** [comment]
this is it! :dancers: 

With this release all our files are getting through without issue.
Thanks again, especially for being such a good sport, and getting everything sorted so quickly.

ps: For now, I'm repackaging TinyCsvParser in my own private nuget feed.
Could you let us know when you are planning to make a new nuget release?

**Comment by bytefish** [comment]
Great! Thanks for the Feedback. 😎 I will create a new NuGet package this
evening and close this issue. 🙌

**Comment by bytefish** [comment]
I have uploaded Version 1.3 to NuGet:

* [https://www.nuget.org/packages/TinyCsvParser/1.3.0](https://www.nuget.org/packages/TinyCsvParser/1.3.0)

I am closing the ticket. Please let me know and reopen, if there are problems with the release.
